version: '3'

services: 

  back:
    build: ./server
    container_name: server
    restart: always
    ports: 
      - "5000:5000"
    depends_on:
      - mongo


  mongo:
    image: mongo
    restart: always
    container_name: my_mongo
    ports:
      - 27017:27017



