version: '3'

services: 
  nginx:
    image: nginx:latest
    restart: always
    ports: 
      - "80:80"
    container_name: nginx-front
    depends_on:
      - mongo
    volumes:
      - ./static:/usr/share/nginx/html

  back:
    build: ./server
    container_name: server
    restart: always
    ports: 
      - "5000:5000"
    depends_on:
      - mongo


  mongo:
    image: mongo
    restart: always
    container_name: my_mongo
    ports:
      - 27017:27017



